import VO_JSON from "../narration.timing.promo.json";

export interface VoLine {
  start: number;
  end: number;
  phrases: number[];
}
/** Narration timing (seconds), generated by scripts/voice.py promo. */
export const VO = VO_JSON as unknown as Record<keyof typeof VO_JSON, VoLine>;

/**
 * The score runs at 120 BPM from the downbeat on "…into signal": every big
 * picture event sits on a beat, so music, sound and image hit together.
 */
export const B0 = VO.signal.phrases[1];
export const beat = (k: number) => B0 + 0.5 * k;

/** Film beats (seconds). */
export const S = {
  freeze: 5.55, // the storm stops dead
  glow: 5.7, // six letters light up inside the noise
  fly: 6.0, // …and leave it, to become the name
  ignite: B0, // the name collapses into a line of light
  scan: B0 + 0.12, // the line sweeps the frame: noise → order
  rows: beat(2) + 0.02, // the inbox takes over (DOM)
  sort: VO.reads.phrases[1], // 312 → 2
  dive: beat(7), // into Luka's email
  phrase: beat(11), // "Thursday at 14:30" lifts off the reply
  land: beat(12), // …and lands in the week
  lanes: beat(17), // the hour lines become agents
  pillar: beat(24), // the lanes fold into a beam
  one: VO.one.phrases[1], // "working as one"
  implode: beat(31),
  bloom: beat(32), // everything collapses into light
  ring: beat(37) - 0.05, // the thread draws the mark
  flood: beat(39), // through the mark, into daylight
  end: 30,
};
