import VO_JSON from "../narration.timing.mosaic.json";

export interface VoLine {
  start: number;
  end: number;
  phrases: number[];
}
/** Narration timing (seconds), generated by scripts/voice.py mosaic. */
export const VO = VO_JSON as unknown as Record<keyof typeof VO_JSON, VoLine>;

/** "Mail, calendar, finance, documents… one system, thinking together." — word onsets measured on the take. */
const SY = VO.system.start;
export const WORDS = { mail: SY, calendar: SY + 0.38, finance: SY + 0.8, documents: SY + 1.12, one: SY + 1.65, together: SY + 3.0 };

/** Beats of the film (seconds). */
export const T = {
  pull: 0.5, // the camera leaves the first tile: the wall
  tilt: 2.2, // the wall lies down; the camera races along it
  reset: 5.55, // every tile flips blank at once — silence
  wave: VO.together.start - 0.05, // a cobalt wave from one tile
  letters: VO.together.start + 0.55, // tiles spell the name
  burst: 8.1, // the cobalt wall bursts open toward the camera
  bento: 8.8, // …onto the porcelain app
  sort: VO.matter.start + 0.35, // the inbox sorts itself
  lift: VO.writes.start - 0.45, // Luka's mail lifts off and travels
  write: VO.writes.start + 0.05, // the reply builds itself, letter by letter
  chip: VO.time.start - 0.3, // "Thu 14:30" leaves the reply
  slide: VO.time.start + 0.35, // the week slides open
  agents: VO.agents.start - 0.05, // three agents drop out of the calendar
  kpi: 18.2,
  night: 19.15, // the studio goes dark: the system
  rise: WORDS.mail - 0.1, // the modules rise as towers
  one: WORDS.one,
  together: WORDS.together,
  retract: 23.35, // towers sink back into tiles
  picture: VO.picture.start, // the tiles become a picture: the mark
  resolve: VO.picture.start + 0.7, // …in ever finer pieces
  mark: 25.85, // one piece: the vector mark
  word: VO.brand.start, // ASTRYA, flap by flap
  tag: VO.brand.start + 0.67,
  cta: 28.25,
  end: 30,
};
