import EN from "./narration.timing.en.json";
import FR from "./narration.timing.fr.json";
import SH from "./narration.timing.short.json";
import { SHORT } from "./core/stage";

/**
 * Language of the cut (`?lang=fr`). Only the narrative layer is localised —
 * voice-over, titles, kinetic words, captions, tagline and call to action.
 * The product UI shown in the film stays as the product ships it.
 */
export const LANG: "en" | "fr" = new URLSearchParams(location.search).get("lang") === "fr" ? "fr" : "en";

export interface VoLine {
  start: number;
  end: number;
  phrases: number[];
  captions: string[];
}
/** Narration timing (film seconds), generated by scripts/voice.py. */
export const VO = (SHORT ? SH : LANG === "fr" ? FR : EN) as unknown as Record<keyof typeof EN, VoLine>;

const COPY = {
  en: {
    titleA: "Your work arrives from everywhere.",
    titleB: "All at once.",
    kin: ["Emails.", "Meetings.", "Invoices."],
    reads: ["Reads.", "Prioritizes.", "Understands."],
    voice: "In your voice.",
    work: "Handled. In parallel.",
    brandLine: "The calm layer above all your work.",
    tagline: "Intelligence that works with you.",
    cta: "Discover ASTRYA",
  },
  fr: {
    titleA: "Votre travail arrive de partout.",
    titleB: "Tout, en même temps.",
    kin: ["Messages.", "Réunions.", "Factures."],
    reads: ["Elle lit.", "Elle priorise.", "Elle comprend."],
    voice: "Avec vos mots.",
    work: "Géré. En parallèle.",
    brandLine: "Le calme, au-dessus de tout votre travail.",
    tagline: "L'intelligence qui travaille avec vous.",
    cta: "Découvrir ASTRYA",
  },
};
export const TXT = COPY[LANG];

/** Film times at which the noise scene's kinetic words land: emails · meetings · invoices · all at once. */
export function listBeats(): [number, number, number, number] {
  const K = VO.atonce.phrases;
  if (K.length >= 4) return [K[0], K[1], K[2], K[3]];
  return [K[0], (K[0] + K[1]) / 2 + 0.02, K[1], K[2]];
}

/** In/out (film time) of "In your voice." — on the phrase that says it. */
export function voiceBeat(): [number, number] {
  const v = VO.voice;
  if (SHORT) return [v.phrases[1] + 0.05, Math.min(v.end + 0.5, 14.0)]; // out before the cut at 14.3
  if (LANG === "fr") return [v.phrases[1] + 0.05, v.phrases[2] + 0.6];
  return [v.start + 1.1, v.phrases[1] + 0.6];
}
